//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilizandoAspNetUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arma
    {
        public int IdArma { get; set; }
        public string ArmaDescricao { get; set; }
        public decimal Dano { get; set; }
        public decimal Durabilidade { get; set; }
        public decimal Precisao { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Alcance { get; set; }
        public int TipoMunicaoID { get; set; }
        public Nullable<int> QtdeMunicao { get; set; }
        public int CategoriaID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoMunicao TipoMunicao { get; set; }
            }
}
